# base16-schemes

## Contributing

To submit your scheme, submit a new pull request to this repository with your
scheme yaml file.

## Imported Scheme Repositories

These are the original locations all schemes were imported from. (this list generated by `doc/generate_main_readme.sh` script)

${SCHEMES}

[**Old Unclaimed Schemes**](https://github.com/chriskempson/base16-unclaimed-schemes) - If your scheme is in this repository, please give it a new home!

## FAQ

***Where did these all come from?***

These schemes were originally imported from [the old schemes source repo](https://github.com/chriskempson/base16-schemes-source) on May 25th, 2022 around 11pm UTC.

***Why is it all in one repo now?***

Spec 0.10 was merged at the same time that base16 was forked from [Chris Kempson's](https://github.com/chriskempson) account. One of the changes of this version was moving all schemes to a single repo rather than separate repos and the fork was chosen as a convenient time to do this.

## Contributors

${CONTRIBUTORS}